# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:6

stages:
    - build

before_script:
    - apt-get update && apt-get install -y ruby ruby-dev yarn
    - gem install sass compass --no-ri --no-rdoc
    - yarn install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - bower_components/
  key: "$CI_BUILD_REPO"


build:
    stage: build
    only:
        - tags
    script:
        - node_modules/.bin/grunt build
    artifacts:
        paths:
            - dist/
